#!/usr/bin/env node
/**
 * ingest.js — continuous recording (RECORDING.md): whoever records a fact ingests it in the same push.
 * Usage: node tools/ingest.js init                 the sweeper switches this memory to continuous recording
 *        node tools/ingest.js index                regenerate the page list in knowledge/index.md
 *        node tools/ingest.js log --op ingest|fix|lint --title "<text>" [--source <path>] [--touched a.md,b.md] [--who X]
 *                                                  append one entry to knowledge/log.md (touched: relative to knowledge/)
 *        node tools/ingest.js check [--who X] [--base <ref>]
 *                                                  the push gate, zero tokens: exit 0 ok · 1 problems listed
 *
 * check looks at the staged state against the remote last pulled (no remote: the last commit):
 * every log entry added is by the member pushing, its source and touched pages exist; every changed
 * page under knowledge/ (not index.md, log.md, sources/) is named in an added entry's touched:; every
 * claim line of an added entry's source stands in knowledge/ verbatim; index.md is current; the
 * touched pages hold no malformed claim line and no broken link. Node built-ins only.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { detectMember } = require('./detect-member');
const { checkClaims } = require('./claims');
const { brokenLinks } = require('./verify-links');

const ROOT = path.resolve(__dirname, '..');
const LOG = 'knowledge/log.md';
const INDEX = 'knowledge/index.md';
const START = '<!-- index:start — generated by `node tools/ingest.js index`; do not edit by hand -->';
const END = '<!-- index:end -->';
const EMPTY_TREE = '4b825dc642cb6eb9a060e54bf8d69288fbee4904'; // git's empty tree: no commit yet
const UNION = ['knowledge/log.md merge=union', 'knowledge/index.md merge=union'];
const LOG_HEAD = '# Log\n\nOne entry per ingest, fix or lint, oldest first, written with `node tools/ingest.js log`; never edited.\n';
const CLAIM = /^\s*-\s+\[(?:measurement|calculation|decision|estimate)\]\s+.+$/;
const norm = (s) => s.trim().replace(/\s+/g, ' ');
const plain = (s) => norm(s.replace(/~~/g, ''));
const eol = (s) => s.replace(/\r\n/g, '\n');
const posix = (p) => p.split(path.sep).join('/');
const readText = (p) => { try { return eol(fs.readFileSync(p, 'utf8')); } catch { return null; } };
const cfgPath = (root) => path.join(root, '.memory', 'config.json');
const readCfg = (root) => JSON.parse(fs.readFileSync(cfgPath(root), 'utf8').replace(/^﻿/, ''));
const git = (root, ...a) => spawnSync('git', ['-C', root, ...a], { encoding: 'utf8' });

function today() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

// ---- index ------------------------------------------------------------------------

/** Record pages under knowledge/, relative to it: not index.md, log.md, READMEs or sources/. */
function recordPages(root) {
  const out = [];
  (function walk(dir) {
    let es = [];
    try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of es) {
      if (e.name.startsWith('.')) continue;
      const p = path.join(dir, e.name);
      const rel = posix(path.relative(path.join(root, 'knowledge'), p));
      if (e.isDirectory()) { if (rel !== 'sources') walk(p); continue; }
      if (!e.isFile() || !e.name.endsWith('.md') || e.name === 'README.md' || rel === 'index.md' || rel === 'log.md') continue;
      out.push(rel);
    }
  })(path.join(root, 'knowledge'));
  return out.sort();
}

function titleOf(text, rel) {
  const fm = /^---\n([\s\S]*?)\n---/.exec(text);
  const t = fm && /^title:[ \t]*(.+)$/m.exec(fm[1]);
  if (t) return t[1].trim().replace(/^["']|["']$/g, '');
  const h = /^#\s+(.+?)\s*$/m.exec(fm ? text.slice(fm[0].length) : text);
  return h ? h[1] : path.posix.basename(rel, '.md');
}

function indexBlock(root) {
  const lines = recordPages(root).map((rel) => {
    const title = titleOf(readText(path.join(root, 'knowledge', rel)) || '', rel).replace(/[[\]\\]/g, '\\$&');
    return `- [${title}](${rel.split('/').map(encodeURIComponent).join('/')})`;
  });
  return [START, ...lines, END].join('\n');
}

/** The index file as it should be: its hand-written head, then the generated block. */
function wantedIndex(root) {
  const cur = readText(path.join(root, INDEX)) || '# Knowledge\n';
  const at = cur.indexOf('<!-- index:start');
  const head = (at === -1 ? cur : cur.slice(0, at)).replace(/\s*$/, '');
  return `${head}\n\n${indexBlock(root)}\n`;
}

function writeIndex(root) {
  const want = wantedIndex(root);
  if (readText(path.join(root, INDEX)) === want) return false;
  fs.writeFileSync(path.join(root, INDEX), want, 'utf8');
  return true;
}

// ---- log ----------------------------------------------------------------------------

function entryText({ op, title, by, source, touched, day }) {
  const fields = [`by: ${by}`, source && `source: ${source}`].filter(Boolean).join(' · ');
  const t = (touched || []).length ? `\ntouched: ${touched.join(', ')}` : '';
  return `## [${day}] ${op} | ${norm(title)}\n${fields}${t}\n`;
}

/** Entries of a log text: { block, day, op, title, by, source, touched[] }. */
function parseLog(text) {
  const out = [];
  const lines = eol(text || '').split('\n');
  for (let i = 0; i < lines.length; i++) {
    const h = /^## \[(\d{4}-\d{2}-\d{2})\] ([a-z-]+) \| (.+)$/.exec(lines[i]);
    if (!h) continue;
    let j = i + 1;
    while (j < lines.length && !/^## \[/.test(lines[j])) j++;
    const body = lines.slice(i + 1, j).join('\n');
    const field = (k) => ((new RegExp('(?:^|[\\s·])' + k + ':[ \\t]*([^·\\n]+)', 'm').exec(body) || [])[1] || '').trim();
    const touched = field('touched').split(',').map((s) => s.trim().replace(/^knowledge\//, '')).filter(Boolean);
    out.push({ block: norm(lines.slice(i, j).join('\n')), day: h[1], op: h[2], title: h[3].trim(),
      by: field('by'), source: field('source'), touched });
    i = j - 1;
  }
  return out;
}

function appendLog(root, entry) {
  const p = path.join(root, LOG);
  const cur = readText(p);
  const base = cur === null ? LOG_HEAD : cur.replace(/\s*$/, '\n');
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, `${base}\n${entryText(entry)}`, 'utf8');
}

// ---- init -----------------------------------------------------------------------------

/** Switch a memory to continuous recording; returns the files written, [] when it already was. */
function init(root, who) {
  const cfg = readCfg(root);
  if (cfg.recording === 'continuous') return [];
  if (who !== cfg.sweeper) throw new Error(`only the sweeper (${cfg.sweeper}) switches this memory to continuous recording; you are ${who || 'unknown'}`);
  cfg.recording = 'continuous';
  fs.writeFileSync(cfgPath(root), JSON.stringify(cfg, null, 2) + '\n', 'utf8');
  const ga = path.join(root, '.gitattributes');
  const cur = readText(ga) || '';
  const add = UNION.filter((l) => !cur.split('\n').includes(l));
  if (add.length) fs.writeFileSync(ga, `${cur}${cur && !cur.endsWith('\n') ? '\n' : ''}# continuous recording: both sides of every append are kept\n${add.join('\n')}\n`, 'utf8');
  appendLog(root, { op: 'migrate', title: 'continuous recording on', by: who, day: today() });
  writeIndex(root);
  return ['.memory/config.json', '.gitattributes', LOG, INDEX];
}

// ---- check ----------------------------------------------------------------------------

function defaultBase(root) {
  if (git(root, 'rev-parse', '--abbrev-ref', '@{u}').status === 0) return git(root, 'merge-base', 'HEAD', '@{u}').stdout.trim();
  return git(root, 'rev-parse', '--verify', '-q', 'HEAD').status === 0 ? 'HEAD' : null;
}

function check(root, me, { base = defaultBase(root) } = {}) {
  const errors = [];
  const before = base ? (git(root, 'show', `${base}:${LOG}`).stdout || '') : '';
  const had = new Set(parseLog(before).map((e) => e.block));
  const added = parseLog(readText(path.join(root, LOG)) || '').filter((e) => !had.has(e.block));
  const diffArgs = ['diff', '--cached', '--name-only', base || EMPTY_TREE, '--', 'knowledge'];
  const changed = git(root, ...diffArgs).stdout.split('\n').map((s) => s.trim()).filter(Boolean)
    .filter((f) => f !== LOG && f !== INDEX && !f.startsWith('knowledge/sources/'));
  const touched = new Set(added.flatMap((e) => e.touched.map((t) => `knowledge/${t}`)));

  const have = new Set();
  for (const rel of recordPages(root)) for (const l of (readText(path.join(root, 'knowledge', rel)) || '').split('\n')) if (CLAIM.test(l)) have.add(plain(l));
  let carried = 0;
  for (const e of added) {
    const name = `log entry "${e.title}"`;
    if (e.by !== me) errors.push(`${name}: by: ${e.by || '(none)'}, but you are ${me}`);
    if (e.op === 'ingest' && !e.source) errors.push(`${name}: an ingest names its source:`);
    for (const t of e.touched) if (!fs.existsSync(path.join(root, 'knowledge', t))) errors.push(`${name}: touched page knowledge/${t} does not exist`);
    if (!e.source) continue;
    const src = readText(path.join(root, e.source));
    if (src === null) { errors.push(`${name}: source ${e.source} does not exist`); continue; }
    for (const l of src.split('\n').filter((x) => CLAIM.test(x))) {
      if (have.has(plain(l))) carried++;
      else errors.push(`${name}: claim line not in knowledge/: ${(/\]\s+(.+?)\s+->/.exec(l) || [, norm(l)])[1]}`);
    }
  }
  for (const f of changed) if (!touched.has(f)) errors.push(`${f} changed but no log entry names it in touched:`);
  if (readText(path.join(root, INDEX)) !== wantedIndex(root)) errors.push(`${INDEX} is not current — node tools/ingest.js index`);
  const pages = new Set([...changed, ...touched]);
  for (const e of checkClaims(root).errors) if (pages.has(e.split(':')[0])) errors.push(e);
  for (const b of brokenLinks(root)) if (pages.has(b.split(':')[0])) errors.push(`broken link ${b}`);
  return { errors, entries: added.length, pages: pages.size, carried };
}

const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;
function checkLine(r) {
  if (r.errors.length) return [...r.errors.map((e) => '  ' + e), `ingest check: ${plural(r.errors.length, 'problem', 'problems')}`].join('\n');
  if (!r.entries && !r.pages) return 'ingest check: nothing to check';
  return `ingest check: ok — ${plural(r.entries, 'entry', 'entries')}, ${plural(r.pages, 'page', 'pages')}, ${plural(r.carried, 'claim line', 'claim lines')} carried`;
}

module.exports = { recordPages, indexBlock, wantedIndex, writeIndex, parseLog, entryText, appendLog, init, check, checkLine, today, LOG, INDEX };

if (require.main === module) {
  const [cmd, ...args] = process.argv.slice(2);
  const opt = (n) => { const i = args.indexOf(n); return i === -1 ? undefined : args[i + 1]; };
  const die = (m) => { console.error(`ingest: ${m}`); process.exit(1); };
  const who = () => opt('--who') || detectMember(ROOT) || die('who is this? write your first name, lowercase, into .memory/me');
  if (cmd === 'init') {
    let files;
    try { files = init(ROOT, who()); } catch (e) { die(e.message); }
    console.log(files.length ? `continuous recording on — ${files.join(', ')}; push it with node tools/sync.js --push --sweep` : 'already continuous — nothing written');
  } else if (cmd === 'index') {
    console.log(writeIndex(ROOT) ? `index: ${recordPages(ROOT).length} page(s) listed` : 'index: unchanged');
  } else if (cmd === 'log') {
    const op = opt('--op'), title = opt('--title');
    if (!['ingest', 'fix', 'lint'].includes(op)) die('--op ingest|fix|lint');
    if (!title) die('--title "<what was recorded>"');
    const touched = String(opt('--touched') || '').split(',').map((s) => s.trim().replace(/^knowledge\//, '')).filter(Boolean);
    const entry = { op, title, by: who(), source: opt('--source'), touched, day: today() };
    appendLog(ROOT, entry);
    console.log(entryText(entry).trim());
  } else if (cmd === 'check') {
    const r = check(ROOT, who(), opt('--base') ? { base: opt('--base') } : {});
    console.log(checkLine(r));
    process.exit(r.errors.length ? 1 : 0);
  } else {
    die('usage: node tools/ingest.js init | index | log --op … --title … | check');
  }
}
