#!/usr/bin/env node
/**
 * secret.js — this memory's own vault: one secret, called by name. No Joserah needed.
 * Store: keys/secrets.json, flat name -> value; keys/ is gitignored and never leaves the machine.
 *   node tools/secret.js <name>          prints the value — only ever inside $(...)
 *   node tools/secret.js --set <name>    in a terminal asks for the value, echo off; or the value on stdin
 *   node tools/secret.js --list | --has <name> | --remove <name>
 *   node tools/secret.js --index         writes .memory/vault-index.md, names only
 * Names: lowercase, dot-separated, at least two parts — <company>.<system>.<field>.
 * Exit: 0 ok · 1 usage · 2 no such name · 3 store unreadable. Node built-ins only.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const STORE = path.join(ROOT, 'keys', 'secrets.json');
const INDEX = path.join(ROOT, '.memory', 'vault-index.md');
const NAME = /^[a-z0-9-]+(\.[a-z0-9-]+)+$/;
const die = (code, msg) => { process.stderr.write(msg + '\n'); process.exit(code); };

let secrets = {};
if (fs.existsSync(STORE)) {
  try { secrets = JSON.parse(fs.readFileSync(STORE, 'utf8').replace(/^﻿/, '')); } catch (e) { die(3, 'secret: store unreadable (' + e.message + ')'); }
}
const has = (k) => Object.prototype.hasOwnProperty.call(secrets, k);

function writeIndex() {
  fs.mkdirSync(path.dirname(INDEX), { recursive: true });
  fs.writeFileSync(INDEX, '# Vault index — names only (generated by tools/secret.js --index)\n\n' +
    Object.keys(secrets).sort().map((n) => '- ' + n).join('\n') + '\n');
}
function save() {
  fs.mkdirSync(path.dirname(STORE), { recursive: true });
  fs.writeFileSync(STORE + '.tmp', JSON.stringify(secrets, null, 2) + '\n');
  fs.renameSync(STORE + '.tmp', STORE);
  writeIndex();
}

const args = process.argv.slice(2);
if (!args.length) die(1, 'secret: give a name, or --list');
const [cmd, name] = args;

if (cmd === '--index') { writeIndex(); console.log('index: ' + Object.keys(secrets).length + ' names'); }
else if (cmd === '--list') Object.keys(secrets).sort().forEach((k) => console.log(k));
else if (cmd === '--has') { if (!name) die(1, 'secret: --has needs a name'); console.log(has(name) ? 'present' : 'absent'); process.exit(has(name) ? 0 : 2); }
else if (cmd === '--remove') { if (!has(name)) die(2, 'secret: no such name'); delete secrets[name]; save(); console.log('removed ' + name); }
else if (cmd === '--set') {
  if (!name || !NAME.test(name)) die(1, 'secret: name must be <company>.<system>.<field> (lowercase letters, digits, hyphens)');
  if (has(name) && !args.includes('--force')) die(1, `secret: "${name}" already exists; --force to overwrite`);
  const store = (value) => { secrets[name] = value; save(); console.log('saved: ' + name); };
  if (process.stdin.isTTY) {
    const rl = require('readline').createInterface({ input: process.stdin, output: process.stderr, terminal: true });
    const q = `Value for ${name}: `;
    rl._writeToOutput = (s) => { if (s.includes(q)) process.stderr.write(q); };
    rl.question(q, (typed) => { rl.close(); process.stderr.write('\n'); if (!typed) die(1, 'secret: nothing typed, nothing saved'); store(typed); });
  } else {
    const value = fs.readFileSync(0, 'utf8').replace(/\r?\n$/, '');
    if (!value) die(1, 'secret: stdin is empty');
    store(value);
  }
} else {
  if (!has(cmd)) die(2, `secret: "${cmd}" not found`);
  process.stdout.write(String(secrets[cmd]));
}
