#!/usr/bin/env node
/**
 * secret.js — this memory's own vault: one secret, called by name. No Joserah needed.
 * Store: keys/secrets.json, flat name -> value; keys/ is gitignored and never leaves the machine.
 *   node tools/secret.js <name>          prints the value — only ever inside $(...)
 *   node tools/secret.js --set <name>    no value on stdin: a Joserah Vault window on this machine, the terminal
 *                                        (echo off) over SSH/remote/headless; --tty / --dialog force either
 *   node tools/secret.js --list | --has <name> | --remove <name>
 *   node tools/secret.js --index         writes .memory/vault-index.md, names only
 * Names: lowercase, dot-separated, at least two parts — <company>.<system>.<field>.
 * Exit: 0 ok · 1 usage · 2 no such name · 3 store unreadable. Node built-ins only.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const STORE = path.join(ROOT, 'keys', 'secrets.json');
const INDEX = path.join(ROOT, '.memory', 'vault-index.md');
const NAME = /^[a-z0-9-]+(\.[a-z0-9-]+)+$/;
const die = (code, msg) => { process.stderr.write(msg + '\n'); process.exit(code); };

let secrets = {};
if (fs.existsSync(STORE)) {
  try { secrets = JSON.parse(fs.readFileSync(STORE, 'utf8').replace(/^﻿/, '')); } catch (e) { die(3, 'secret: store unreadable (' + e.message + ')'); }
}
const has = (k) => Object.prototype.hasOwnProperty.call(secrets, k);

function writeIndex() {
  fs.mkdirSync(path.dirname(INDEX), { recursive: true });
  fs.writeFileSync(INDEX, '# Vault index — names only (generated by tools/secret.js --index)\n\n' +
    Object.keys(secrets).sort().map((n) => '- ' + n).join('\n') + '\n');
}
function save() {
  fs.mkdirSync(path.dirname(STORE), { recursive: true });
  fs.writeFileSync(STORE + '.tmp', JSON.stringify(secrets, null, 2) + '\n');
  fs.renameSync(STORE + '.tmp', STORE);
  writeIndex();
}

const args = process.argv.slice(2);
if (!args.length) die(1, 'secret: give a name, or --list');
const [cmd, name] = args;

if (cmd === '--index') { writeIndex(); console.log('index: ' + Object.keys(secrets).length + ' names'); }
else if (cmd === '--list') Object.keys(secrets).sort().forEach((k) => console.log(k));
else if (cmd === '--has') { if (!name) die(1, 'secret: --has needs a name'); console.log(has(name) ? 'present' : 'absent'); process.exit(has(name) ? 0 : 2); }
else if (cmd === '--remove') { if (!has(name)) die(2, 'secret: no such name'); delete secrets[name]; save(); console.log('removed ' + name); }
else if (cmd === '--set') {
  if (!name || !NAME.test(name)) die(1, 'secret: name must be <company>.<system>.<field> (lowercase letters, digits, hyphens)');
  if (has(name) && !args.includes('--force')) die(1, `secret: "${name}" already exists; --force to overwrite`);
  const store = (value) => { secrets[name] = value; save(); console.log('saved: ' + name); };
  // No value on stdin (a terminal, or an empty stdin as when the assistant runs this): on this machine a
  // Joserah Vault window asks for it; over SSH, remote or headless, the terminal. --tty / --dialog force either.
  let piped = '';
  if (!process.stdin.isTTY) { try { piped = fs.readFileSync(0, 'utf8').replace(/\r?\n$/, ''); } catch { /* no stdin */ } }
  const dialog = require(path.join(__dirname, 'lib', 'vault-dialog.js'));
  const local = !piped && dialog.canShowDialog();
  if (piped) store(piped);
  else if (args.includes('--dialog') && !local) die(1, 'secret: the Joserah Vault window cannot open here (SSH, remote session, headless or no browser) — drop --dialog');
  else if (local && !args.includes('--tty')) {
    let cfg = {};
    try { cfg = JSON.parse(fs.readFileSync(path.join(ROOT, '.memory', 'config.json'), 'utf8')); } catch { /* defaults */ }
    const lang = /^(tr|turk|türk)/i.test(cfg.language || '') ? 'tr' : 'en';
    dialog.askSecret({ name, lang, brand: { kind: 'company', dir: path.join(ROOT, '.brand'), name: cfg.company } }).then((value) => {
      if (!value) { console.log('cancelled'); process.exit(1); }
      store(value);
    });
  } else if (process.stdin.isTTY) {
    const rl = require('readline').createInterface({ input: process.stdin, output: process.stderr, terminal: true });
    const q = `Value for ${name}: `;
    rl._writeToOutput = (s) => { if (s.includes(q)) process.stderr.write(q); };
    rl.question(q, (typed) => { rl.close(); process.stderr.write('\n'); if (!typed) die(1, 'secret: nothing typed, nothing saved'); store(typed); });
  } else die(1, 'secret: stdin is empty');
} else {
  if (!has(cmd)) die(2, `secret: "${cmd}" not found`);
  process.stdout.write(String(secrets[cmd]));
}
