#!/usr/bin/env node
/**
 * secret.js — the workspace vault: one secret, called by name.
 *
 * A password standing in a note is seen by everything that reads the note.
 * Values live in keys/secrets.json as name -> value and are called from here
 * one at a time; notes carry only the NAME. If a real vault replaces this file
 * one day, only its inside changes — the call shape and the names stay.
 *
 * Usage (scaffold copies this file to .joserah/tools/secret.js):
 *   node .joserah/tools/secret.js --list                  names only, never a value
 *   node .joserah/tools/secret.js --has <name>            present/absent, no value
 *   node .joserah/tools/secret.js <name>                  prints the value — only ever inside $(...)
 *   node .joserah/tools/secret.js --set <name> [--force]   in a terminal: asks for the value, echo off
 *   <value> | node .joserah/tools/secret.js --set <name> [--force]
 *                                                         value from stdin, never echoed
 *   node .joserah/tools/secret.js --index                 writes .joserah/vault-index.md, names only
 *   node .joserah/tools/secret.js --import <file> [--prefix <scope>] [--delete] [--replace --yes]
 *                                                         a foreign vault (.json, any nesting, or a record
 *                                                         array — needs --prefix) or .env into names; lists
 *                                                         names, never values; never overwrites (conflict =
 *                                                         skipped, exit 1); --replace --yes empties the store
 *                                                         first; a file that is not a vault (service-account
 *                                                         key, PEM, other JSON) is refused, exit 4
 *   node .joserah/tools/secret.js --rename <old> <new>    correct a name without seeing the value
 *
 * Embed, never print:
 *   curl -H "Authorization: Bearer $(node .joserah/tools/secret.js acme.api.api-token)" ...
 *
 * Names: lowercase, dot-separated, at least two parts — <scope>.<system>[.<sub>].<field>,
 * field one of host|port|url|user|password|token|api-token|pin|ssid|serial|note ...
 *
 * Exit: 0 ok · 1 usage error · 2 no such name · 3 store unreadable / no workspace · 4 not a vault.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const MARKER = path.join('.joserah', 'config.json');
const README = 'Vault. Values are read only through .joserah/tools/secret.js and only ever embedded in a command as $(...). Never print, copy or cite a value; notes carry the name.';
const NAME = /^[a-z0-9-]+(\.[a-z0-9-]+)+$/;

function die(code, msg) { process.stderr.write(msg + '\n'); process.exit(code); }

function findWorkspace(start) {
  for (let dir = path.resolve(start); ; dir = path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, MARKER))) return dir;
    if (path.dirname(dir) === dir) return null;
  }
}

// The workspace copy (.joserah/tools/secret.js) belongs to the workspace two
// levels up, wherever it is called from; the plugin copy serves the cwd's.
const beside = path.resolve(__dirname, '..', '..');
const ROOT = fs.existsSync(path.join(beside, MARKER)) ? beside : findWorkspace(process.cwd());
if (!ROOT) die(3, 'secret: not inside a Joserah workspace (no .joserah/config.json found)');
const STORE = path.join(ROOT, 'keys', 'secrets.json');
const INDEX = path.join(ROOT, '.joserah', 'vault-index.md');
// Commands that may run before the first secret exists.
const NO_STORE_OK = ['--set', '--index', '--import'];

const args = process.argv.slice(2);
if (!args.length) die(1, 'secret: give a name, or --list');

let doc = { _readme: README, secrets: {} };
if (fs.existsSync(STORE)) {
  try {
    doc = JSON.parse(fs.readFileSync(STORE, 'utf8').replace(/^﻿/, ''));
  } catch (err) {
    die(3, 'secret: store unreadable (' + err.message + ')');
  }
} else if (!NO_STORE_OK.includes(args[0])) {
  die(3, 'secret: no store yet — keys/secrets.json is created by the first --set');
}
const standard = (d) => d && typeof d === 'object' && d.secrets && typeof d.secrets === 'object' && !Array.isArray(d.secrets);
// A store in some other shape would list nothing and a --set would mix into it.
if (fs.existsSync(STORE) && !standard(doc)) {
  die(3, 'secret: keys/secrets.json is not in the standard shape — the update migration imports it (/joserah:update)');
}
const secrets = (doc && doc.secrets) || {};
const has = (k) => Object.prototype.hasOwnProperty.call(secrets, k);

// The one file the assistant may read to know what exists: names grouped by
// scope, never a value. Rewritten after every change to the store.
function writeIndex() {
  const groups = {};
  for (const k of Object.keys(secrets).sort()) (groups[k.split('.')[0]] ||= []).push(k);
  let text = '# Vault index — names only (generated by secret.js --index)\n';
  for (const [scope, names] of Object.entries(groups)) {
    text += `\n## ${scope}\n\n${names.map((n) => '- ' + n).join('\n')}\n`;
  }
  fs.mkdirSync(path.dirname(INDEX), { recursive: true });
  fs.writeFileSync(INDEX, text);
}

// Store write: .bak of the previous store, atomic rename, then the index.
function save() {
  fs.mkdirSync(path.dirname(STORE), { recursive: true });
  if (fs.existsSync(STORE)) fs.copyFileSync(STORE, STORE + '.bak');
  doc.secrets = secrets;
  fs.writeFileSync(STORE + '.tmp', JSON.stringify(doc, null, 2) + '\n');
  fs.renameSync(STORE + '.tmp', STORE);
  writeIndex();
}

if (args[0] === '--index') {
  writeIndex();
  console.log('index: ' + Object.keys(secrets).length + ' names');
  process.exit(0);
}

if (args[0] === '--list') {
  // Names only, on purpose. This mode never prints a value.
  Object.keys(secrets).sort().forEach((k) => console.log(k));
  process.exit(0);
}

if (args[0] === '--has') {
  if (!args[1]) die(1, 'secret: --has needs a name');
  console.log(has(args[1]) ? 'present' : 'absent');
  process.exit(has(args[1]) ? 0 : 2);
}

// A foreign key -> name part: dots split parts, anything outside [a-z0-9-] becomes '-'.
const parts = (key) => String(key).toLowerCase().split('.')
  .map((p) => p.replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '')).filter(Boolean);

// 0.15.1: a record array — [{ system, kind, username, value, note, ... }], what a
// secret collector writes. Flattening it by index gave 382 useless names
// (`0.value`, `0.found-in.3`). One record: <prefix>.<system>.<field>, the field
// from `kind`; `username` -> .user, `note` -> .note; name, collected, found-in
// and anything else are metadata and are not stored.
const isRecordArray = (d) => Array.isArray(d) && d.length > 0 &&
  d.every((r) => r && typeof r === 'object' && !Array.isArray(r) && 'value' in r);
const slug = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
const FIELDS = { 'api-key': 'api-token', apikey: 'api-token', 'api-token': 'api-token', password: 'password', token: 'token', pin: 'pin' };
const duplicates = [];
function recordEntries(data, pre) {
  const seen = new Map();
  // Same name, different value: -2, -3 ... on the field. Same value: one entry.
  const unique = (name, value) => {
    for (let i = 1; ; i++) {
      const n = i === 1 ? name : `${name}-${i}`;
      if (!seen.has(n) || seen.get(n) === value) {
        if (i > 1 && !seen.has(n)) duplicates.push(`${name} -> ${n}`);
        seen.set(n, value);
        return n;
      }
    }
  };
  const out = [];
  for (const r of data) {
    const base = pre.concat(slug(r.system)).join('.');
    const kind = slug(r.kind);
    const add = (field, v) => {
      if (v === undefined || v === null || typeof v === 'object') return;
      const name = unique(`${base}.${field}`, String(v));
      out.push([name, String(v)]);
    };
    add(FIELDS[kind] || kind, r.value);
    add('user', r.username);
    add('note', r.note);
  }
  return out;
}

// 0.15.1: a file that holds secrets but is not a vault — a service-account key a
// live MCP server reads, a PEM key — is never imported, and neither is a JSON of
// any other shape. `null` means it is a vault.
const MAX_VAULT_BYTES = 512 * 1024;
function notAVault(file, text) {
  if (fs.statSync(file).size > MAX_VAULT_BYTES) return 'larger than 512 KB';
  if (/-----BEGIN [A-Z ]*(PRIVATE KEY|CERTIFICATE)/.test(text)) return 'a PEM or OpenSSH key';
  if (!(/\.json$/i.test(file) || /^\s*[{[]/.test(text))) return null;
  let data;
  try { data = JSON.parse(text); } catch { return 'not valid JSON'; }
  if (data && (data.type === 'service_account' || 'private_key' in Object(data))) return 'a service-account key';
  if (standard(data) || isRecordArray(data)) return null;
  const leavesAreStrings = (n) => n !== null && typeof n === 'object' && !Array.isArray(n) &&
    Object.values(n).every((v) => v === null || ['string', 'number'].includes(typeof v) || leavesAreStrings(v));
  return leavesAreStrings(data) ? null : 'not a name -> value map';
}

// Foreign vault -> [name, value] pairs. JSON: any nesting, keys become parts
// (a standard store is read through its `secrets`); a record array by record.
// Anything else: .env lines.
function entriesOf(file, prefix, text) {
  const pre = prefix ? parts(prefix) : [];
  const out = [];
  // By extension, or by content: a renamed store (secrets.json.imported-<date>) is still JSON.
  if (/\.json$/i.test(file) || /^\s*[{[]/.test(text)) {
    let data = JSON.parse(text);
    if (isRecordArray(data)) {
      if (!pre.length) die(1, 'secret: ' + path.basename(file) + ' is a record array — its names need --prefix <scope>');
      return recordEntries(data, pre);
    }
    if (standard(data)) data = data.secrets;
    (function walk(node, trail) {
      if (node !== null && typeof node === 'object') {
        for (const [k, v] of Object.entries(node)) if (!(trail.length === 0 && k === '_readme')) walk(v, trail.concat(parts(k)));
      } else out.push([pre.concat(trail).join('.'), node === null ? '' : String(node)]);
    })(data, []);
    return out;
  }
  for (const line of text.split(/\r?\n/)) {
    const m = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_.-]*)\s*=\s*(.*?)\s*$/.exec(line);
    if (!m) continue;
    let v = m[2];
    const q = /^(["'])(.*)\1$/.exec(v);
    v = q ? q[2] : v.replace(/\s+#.*$/, '');
    out.push([pre.concat('env', parts(m[1].replace(/_/g, '-'))).join('.'), v]);
  }
  return out;
}

if (args[0] === '--import') {
  const file = args[1] && path.resolve(args[1]);
  if (!file || !fs.existsSync(file)) die(1, 'secret: --import needs an existing file');
  if (file === path.resolve(STORE)) die(1, 'secret: that is the store itself');
  const pi = args.indexOf('--prefix');
  let text;
  try { text = fs.readFileSync(file, 'utf8').replace(/^﻿/, ''); }
  catch (err) { die(1, 'secret: cannot read ' + path.basename(file) + ' (' + err.name + ')'); }
  const why = notAVault(file, text);
  if (why) die(4, `secret: not a vault: ${path.basename(file)} (${why}) — nothing imported, the file is untouched`);
  let entries;
  try { entries = entriesOf(file, pi > 0 ? args[pi + 1] : '', text); }
  catch (err) { die(1, 'secret: cannot read ' + path.basename(file) + ' (' + err.name + ')'); }
  if (!entries.some(([name, value]) => NAME.test(name) && value)) {
    die(4, `secret: not a vault: ${path.basename(file)} (no valid name in it${pi > 0 ? '' : ' — try --prefix'}) — nothing imported`);
  }
  // --replace: the store is emptied first (its .bak keeps the old one). Counted, never done without --yes.
  if (args.includes('--replace')) {
    const count = Object.keys(secrets).length;
    if (!args.includes('--yes')) die(1, `secret: --replace would delete all ${count} name(s) in the store first; add --yes`);
    for (const k of Object.keys(secrets)) delete secrets[k];
    console.log(`replace: ${count} name(s) removed from the store`);
  }
  for (const d of duplicates) console.log(`duplicate ${d}`);
  const n = { imported: 0, unchanged: 0, skipped: 0 };
  for (const [name, value] of entries) {
    // Lines carry names only; a value never reaches stdout or stderr.
    if (!NAME.test(name)) { n.skipped++; console.log(`skipped ${name || '(no name)'}: not a valid name — use --prefix`); }
    else if (!value) { n.skipped++; console.log(`skipped ${name}: empty`); }
    else if (has(name) && secrets[name] === value) { n.unchanged++; console.log(`unchanged ${name}`); }
    else if (has(name)) { n.skipped++; console.log(`skipped ${name}: exists with a different value`); }
    else { secrets[name] = value; n.imported++; console.log(`imported ${name}`); }
  }
  if (n.imported || args.includes('--replace')) save(); else writeIndex();
  console.log(`import: ${n.imported} imported, ${n.unchanged} unchanged, ${n.skipped} skipped`);
  if (n.skipped) process.exit(1);
  if (args.includes('--delete')) fs.rmSync(file);
  process.exit(0);
}

if (args[0] === '--rename') {
  const [from, to] = args.slice(1, 3);
  if (!has(from)) die(2, `secret: "${from}" not found`);
  if (!to || !NAME.test(to)) die(1, 'secret: name must be <scope>.<system>.<field> (lowercase letters, digits, hyphens)');
  if (has(to)) die(1, `secret: "${to}" already exists`);
  secrets[to] = secrets[from];
  delete secrets[from];
  save();
  console.log(`renamed: ${from} -> ${to}`);
  process.exit(0);
}

if (args[0] === '--set') {
  const name = args[1];
  if (!name || !NAME.test(name)) die(1, 'secret: name must be <scope>.<system>.<field> (lowercase letters, digits, hyphens)');
  if (has(name) && !args.includes('--force')) die(1, `secret: "${name}" already exists; --force to overwrite`);
  const store = (value) => {
    secrets[name] = value;
    save();
    console.log('saved: ' + name);
    process.exit(0);
  };
  if (process.stdin.isTTY) {
    // 0.15.1 (owner, 2026-09-30): the owner runs this line in their own
    // terminal, so the value never passes through the assistant. The prompt
    // goes to stderr; what is typed is not echoed.
    const rl = require('readline').createInterface({ input: process.stdin, output: process.stderr, terminal: true });
    const question = `Value for ${name}: `;
    rl._writeToOutput = (s) => { if (s.includes(question)) process.stderr.write(question); };
    rl.question(question, (typed) => {
      rl.close();
      process.stderr.write('\n');
      if (!typed) die(1, 'secret: nothing typed, nothing saved');
      store(typed);
    });
  } else {
    const value = fs.readFileSync(0, 'utf8').replace(/\r?\n$/, '');
    if (!value) die(1, 'secret: stdin is empty');
    store(value);
  }
}

const key = args[0];
// --set on a terminal answers asynchronously, above; nothing below is for it.
if (key !== '--set') {
  if (!has(key)) {
    // Suggesting names helps fix a typo without leaking a value.
    const near = Object.keys(secrets).filter((k) => k.startsWith(key.split('.')[0])).slice(0, 8);
    die(2, `secret: "${key}" not found.` + (near.length ? '\nclose names:\n  ' + near.join('\n  ') : ''));
  }
  process.stdout.write(String(secrets[key]));
}
